[graph]
all-features = true

[licenses]
version = 2
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]

[advisories]
version = 2
unmaintained = "all"
yanked = "deny"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
